<a href="https://colab.research.google.com/github/shubhanshu1995/My-Medium-Articles/blob/master/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Medium Article Link to be added soon !!**

## **Connect with me on:-**
**Linkedin:** [shubhanshu001](https://www.linkedin.com/in/shubhanshu001/) <br />
**Github:** [shubhanshu1995](https://github.com/shubhanshu1995) <br />
**Medium:** [@shubhanshu1995](https://medium.com/@shubhanshu1995) <br />
**Instagram:** [Shubhanshu Singh](https://www.instagram.com/shubhanshu._.singh/) <br />
**Facebook:** [shubhanshu1995](https://www.facebook.com/shubhanshu1995) <br />
**Twitter:** [TheCuriousLad](https://twitter.com/TheCuriousLad) <br />

# **Let's use NumPy**

In [0]:
import numpy as np

# **NumPy Arrays**

## **Let's create NumPy Arrays using python Lists**

In [0]:
just_a_list = [1,2,3]
just_a_list

[1, 2, 3]

In [0]:
np.array(just_a_list)

array([1, 2, 3])

In [0]:
just_a_matrix = [[1,2,3],[4,5,6],[7,8,9]]
just_a_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
np.array(just_a_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **Built-in Methods**

## **arange**
#### **It returns evenly spaced values within a given interval.**

In [0]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## **Zeros and Ones**
### **Let's generate arrays of zeros or ones**

In [0]:
np.zeros(4)

array([0., 0., 0., 0.])

In [0]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones(4)

array([1., 1., 1., 1.])

In [0]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##**linspace**
### **Return evenly spaced numbers over a specified interval.**

In [0]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [0]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

##**eye**

### **Creates an identity matrix**

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Random**
Numpy also has lot of ways to create random number arrays:


## **rand**
### **Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).**

In [0]:
np.random.rand(2)

array([0.01231767, 0.24372946])

In [0]:
np.random.rand(3,3)

array([[0.75250092, 0.7582111 , 0.16155648],
       [0.11020177, 0.51819124, 0.29267394],
       [0.70052998, 0.58651773, 0.80589757]])

## **randn**
### **Return a sample (or samples) from the "Standard Normal" or "Gaussian" distribution. Unlike rand which is uniform:**

In [0]:
np.random.randn(2)

array([ 1.5868519 , -2.72817085])

In [0]:
np.random.randn(4,4)

array([[ 0.24602617, -2.39464955, -0.1382286 ,  1.47872422],
       [ 0.70466341, -0.17408009, -2.22898345,  0.28018941],
       [ 0.57969196,  0.00664889,  1.20221044,  0.47452959],
       [ 0.93939176, -0.07719476, -0.08907384,  1.26465443]])

## **randint**
### **Return random integers from low (inclusive) to high (exclusive).**

In [0]:
np.random.randint(1,100)

84

In [0]:
np.random.randint(1,100,10)

array([85, 30,  2, 72, 40, 86, 18, 46,  3, 24])

# **Array Attributes and Methods**

## **Reshape**
###**Returns an array containing the same data with a new shape.**

In [0]:
arr = np.arange(16)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [0]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## **max,min,argmax,argmin**
### **These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax**

In [0]:
random_arr = np.random.randint(0,50,10)

In [0]:
random_arr

array([16,  8, 40,  7, 15, 39,  0, 15, 20, 35])

In [0]:
random_arr.max()

40

In [0]:


random_arr.argmax()

2

In [0]:
random_arr.min()

0

In [0]:
random_arr.argmin()

6

## **Shape**
### **Shape is an attribute that arrays have (not a method):**

In [0]:
# Vector
arr.shape

(16,)

In [0]:
# Notice the two sets of brackets
arr.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [0]:
arr.reshape(1,16).shape

(1, 16)

In [0]:
arr.reshape(16,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [0]:
arr.reshape(16,1).shape

(16, 1)

## **dtype**
### **You can also grab the data type of the object in the array:**

In [0]:
arr.dtype

dtype('int64')

##**NumPy Indexing and Selection**
###**Now we will learn how to select elements or group of elements from an array**

### **The simplest way of picking up one or more elements from an array looks very similar to python lists**

In [0]:
#Get a value at an index
arr[5]

5

In [0]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

## **Broadcasting**
### **Numpy arrays differ from a normal Python list because of their ability to broadcast:**

In [0]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [0]:
# Reset array, we'll see the reason behid it soon
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [0]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

### Now note the changes also occur in our original array!

In [0]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## **Indexing a 2D array (matrices)**
**The general format is arr_2d[row][col] or arr_2d[row,col].**

In [0]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

#Show
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
#Indexing row
arr_2d[1]

array([4, 5, 6])

In [0]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

4

In [0]:
# Getting individual element value
arr_2d[1,0]

4

In [0]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [0]:
#Shape bottom row
arr_2d[2]

array([7, 8, 9])

In [0]:
#Shape bottom row
arr_2d[2,:]

array([7, 8, 9])

## **Selection**
**Let's briefly go over how to use brackets for selection based on comparison operators.**

In [0]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr1 > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [0]:
bool_arr = arr1 > 5

In [0]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [0]:
arr1[bool_arr]

array([ 6,  7,  8,  9, 10])

In [0]:
arr1[arr1 > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
x = 2
arr1[arr1 > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# **NumPy Operations**

## **Arithmetic**
### **You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:**

In [0]:
arr2 = np.arange(0,10)

In [0]:
arr2 + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
arr2 * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [0]:
arr2 - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr2 / arr2

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [0]:
# Also warning, but not an error instead infinity
1 / arr2

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [0]:
arr2 ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## **Universal Array Functions**
### **Numpy comes with many universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:**

In [0]:
#Taking Square Roots
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
#Calcualting exponential (e^)
np.exp(arr2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [0]:
np.max(arr2) #same as arr.max()

9

In [0]:
np.sin(arr2)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [0]:
np.log(arr2)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## **Vectorization**

In [0]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic= time.time()
c = np.dot(a,b)
toc = time.time()

print("Time taken in vectorized version: "+str(1000 * (toc - tic) )+" ms")

Time taken in vectorized version: 1.483917236328125 ms


## **For loop version**

In [0]:
c = 0

tic = time.time()
for i in range(1000000):
  c += a[i] * b[i]  

toc = time.time()
print("Time taken in for loop version: "+str(1000 *(toc - tic)) + " ms")

Time taken in for loop version: 579.4703960418701 ms
